In [ ]:
import numpy as np 
from sklearn.decomposition import PCA 
from sklearn.preprocessing import StandardScaler


In [15]:
X = np.array([[1,2,3],
             [45,67,89],
             [10,12,56]])

print(X)
# x = StandardScaler().fit_transform(x)
mean_vec = np.mean(x, axis=0)
X_centered = x - mean_vec
print("Matrix Centered","\n",X_centered)


[[ 1  2  3]
 [45 67 89]
 [10 12 56]]
Matrix Centered 
 [[-17.66666667 -25.         -46.33333333]
 [ 26.33333333  40.          39.66666667]
 [ -8.66666667 -15.           6.66666667]]


Covariance


In [10]:
cov_matrix = np.cov(X_centered.T)
print("Covariance Matrix:\n", cov_matrix)


Covariance Matrix:
 [[ 540.33333333  812.5         902.66666667]
 [ 812.5        1225.         1322.5       ]
 [ 902.66666667 1322.5        1882.33333333]]


Eigen Value, Eigen Vector

In [13]:
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
print("\nEigenvectors:\n", eigen_vectors)
print("\nEigenvalues:\n", eigen_values)


Eigenvectors:
 [[-0.3874021  -0.85548137 -0.34361496]
 [-0.57575884  0.51560541 -0.63454931]
 [-0.72001484  0.04798638  0.69229758]]

Eigenvalues:
 [3.42554602e+03 4.14710240e-13 2.22120648e+02]


In [26]:
sorted_index = np.argsort(eigen_values)[::-1]
sorted_eigenvalues = eigen_values[sorted_index]
sorted_eigenvectors = eigen_vectors[:, sorted_index]

k = 1
eigenvector_subset = sorted_eigenvectors[:, 0:k]

X_reduced = np.dot(X_centered, eigenvector_subset)

print("\nOriginal Data Shape:", X.shape)
print("Reduced Data Shape:", X_reduced.shape)
print("\nFirst 5 rows of reduced data:\n", X_reduced[:5])

scaled = StandardScaler()
X_scaled = scaled.fit_transform(X)
pca = PCA(n_components=2)
sk_reduced = pca.fit_transform(X_scaled)
print(sk_reduced)


Original Data Shape: (3, 3)
Reduced Data Shape: (3, 1)

First 5 rows of reduced data:
 [[ 54.59876236]
 [-61.79253095]
 [  7.19376859]]
[[-1.79068655 -0.36867282]
 [ 2.25968879 -0.17857246]
 [-0.46900224  0.54724528]]
