In [1]:
import numpy as np

In [2]:
# basic arryay creation
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# list creation
lst=[1,2,3,4,5,6.5,"hello"]
print(lst)

[1, 2, 3, 4, 5, 6.5, 'hello']


In [4]:
# list to array conversion
arr=np.array(lst)
arr
# converted all data into string means it supports same data only

array(['1', '2', '3', '4', '5', '6.5', 'hello'], dtype='<U32')

In [5]:
# vector list means 1d list
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)
# now convert it into array of metrics 2d array
arr=np.array(l)
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation function


In [6]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [7]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

Random Generation function

In [9]:
arr=np.random.rand(10)
arr

array([0.58762948, 0.29035943, 0.35878414, 0.95071725, 0.59677059,
       0.02116914, 0.63435795, 0.99448084, 0.60796166, 0.89869909])

In [12]:
arr=np.random.randn(10)
arr

array([ 0.39005256, -0.65486005, -0.79216381,  1.54964429,  1.58519936,
        1.63498354, -1.30079511, -2.46940004,  1.12732521,  0.62994757])

In [10]:
arr=np.random.randint(1,20,10)
arr

array([ 3, 19, 15,  2,  1, 18, 19, 14, 17,  5], dtype=int32)

Array Attributes

In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape

(3, 3)

In [14]:
arr.size

9

In [15]:
arr.dtype

dtype('int64')

Array Methods


In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.min()

np.int64(1)

In [20]:
arr.max()

np.int64(9)

In [21]:
arr.sum()

np.int64(45)

In [17]:
np.sum(arr,axis=0)  #column wise sum

array([12, 15, 18])

In [18]:
np.sum(arr,axis=1)  #row wise sum

array([ 6, 15, 24])

In [19]:
arr.mean()

np.float64(5.0)

In [20]:
arr.std()

np.float64(2.581988897471611)

In [21]:
arr.argmin()  #gives index of minimum value
arr.argmax()  #gives index of maximum value

np.int64(8)

Reshaping and Resizing

In [22]:
# reshapping means changing the shape of array without changing data means converting 1d to 2d or 2d to 3d etc 
# resizing means changing the shape with changing data means adding or removing elements as per new shape 
arr=np.arange(1,31)
arr
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

Numpy indexing and sliceing in vectors

In [23]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
arr[4]

np.int64(5)

In [25]:
arr[1:11:2]

array([ 2,  4,  6,  8, 10])

Numpy indexing and sliceing in metrics

In [26]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [27]:
arr[4,5]

np.int64(30)

In [28]:
arr[2:4,1:4]

array([[14, 15, 16],
       [20, 21, 22]])

Boolean indexing

In [29]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])

Array Operations

Arithematic Operation

In [32]:
a1=np.arange(1,6)
a2=np.arange(6,11)

In [38]:
a1+a2
a1-a2
a1*a2
a1/a2
a1//a2
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [39]:
l=[10,20,30,40,50]
arr=np.array(l)
arr+5

array([15, 25, 35, 45, 55])

Deep and shallow copy

In [36]:
# example of deepcopy
a=np.arange(2,11)
a
b=a  #deep copy
b
# means if you change element of b will affect a and same for b if you change a will affect b
# but if we use copy() method then it will be shallow copy means changes in one will not affect other
c=a.copy()  #shallow copy

In [37]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# exmample of shallow copy
a=np.arange(1,11)
a
slice=a[:6]
slice=slice*10
slice

array([10, 20, 30, 40, 50, 60])

Matrix Operation

In [ ]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
a@b  #matrix multiplication
np.dot(a,b)  #another way for matrix multiplication

array([[19, 22],
       [43, 50]])

In [43]:
a.T #transpose of matrix whre rows become columns and columns become rows

array([[1, 3],
       [2, 4]])

Advance array manupulation


stacking

In [39]:
# stacking of arrays can be done in vector manner and not in matrix manner it has to be 1d arrays it has 2 types vertical and horizontal
a=[1,2,3,4,5]
b=[6,7,8,9,10]
np.vstack((a,b))  #vertical stacking of arrays

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.hstack((a,b))  #horizontal stacking of arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.column_stack((a,b))  #column wise stacking of arrays

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

spliting


In [42]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
np.hsplit(c,2)  #horizontal spliting of arrays

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [44]:
np.vsplit(c,2)  #vertical spliting of arrays

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

Valid Sudoku


In [50]:
# example of sudoku validation
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [51]:
b=np.sum(s, axis=1)  #column wise sum
for i in b:
    if i != 45:
        print("Invalid Sudoku")
        break
else:
    print("Valid Sudoku")

Valid Sudoku


In [52]:
c=np.sum(s,axis=0)  #row wise sum
for i in c:
    if i!=45:
        print("Invalid Sudoku")
        break
else:
    print("Valid Sudoku")

Valid Sudoku


In [53]:
for i in range(0,8,3):
    for j in range(0,8,3):
        n=s[i:i+3,j:j+3]
        if np.sum(n)!=45:
            print("Invalid Sudoku")
            break
        else:
            print("Valid Sudoku")

Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku


General Questions

In [45]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [46]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [47]:
#Find the average age of students.
average_age=np.mean(data[:, 0])
average_age

np.float64(18.4)

In [48]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [58]:
#Find the highest Science mark.
science_mark=data[:,2]
np.max(science_mark)

np.int64(95)

In [59]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [60]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [61]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [62]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [63]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80)&(data[:,2]>=80)]


array([[19, 92, 88],
       [20, 90, 85]])

In [64]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])